name: Publish to npm

on:
  push:
    # paths:
    #  - 'package.json'
    branches:
      - master

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'        

      - name: Install dependencies
        if: steps.version_check.outputs.changed == 'true'
        run: npm ci

      - name: Publish to npm
        if: steps.version_check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
